### ISSUE TITLE
Same account launched on diffrent device 

### ISSUE THREAD

**Issue by Acidgag2** [debelopguy/BiomeHopper#4]
when it loads after closing from the biome, it reopens roblox joins the vip then says same account launched on diffrent device then i have to wait for it to be restarted

**Comment by debelopguy** [comment]
when i have time i'll add an option to wait additional time before a rejoin

**Comment by debelopguy** [comment]
sorry for the long wait, "rejoindelay" option has been added in the settings in V1.1c, which waits a bit before opening the link.
